name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Setup Node
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
