name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Setup Node
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
