name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Setup Node
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
